<?php

/**
 * @file
 * Provides Commerce integration with Banca Intesa Serbia payment services.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_banca_intesa_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.commerce_banca_intesa':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Commerce integration with Banca Intesa Serbia payment services.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_mail().
 */
function commerce_banca_intesa_mail($key, &$message, $params) {
  switch ($key) {
    case 'commerce_banca_intesa_payment_report':
      /** @var \Drupal\Core\Render\RendererInterface $renderer */
      $renderer = \Drupal::service('renderer');

      if (isset($params['headers'])) {
        $message['headers'] = array_merge($message['headers'], $params['headers']);
      }
      if (!empty($params['from'])) {
        $message['from'] = $params['from'];
      }
      $message['subject'] = $params['subject'];
      $message['body'][] = $renderer->render($params['body']);
      break;
  }
}

/**
 * Implements hook_theme().
 */
function commerce_banca_intesa_theme($existing, $type, $theme, $path) {
  return [
    'commerce_banca_intesa_payment_report' => [
      'variables' => [
        'order_entity' => NULL,
        'message' => NULL,
        'payment_report' => NULL,
      ],
    ],
  ];
}
